### ISSUE TITLE
Provide a license

### ISSUE THREAD

**Issue by dallasgutauckis** [EddieRingle/android-undergarment#1]
Can you please provide a license for this project?

**Comment by EddieRingle** [comment]
The single drawable resource and source file are licensed individually under the New BSD License, but I suppose it would be wise to provide a global LICENSE file as well. Not sure how I missed that in the first place.

**Comment by dallasgutauckis** [comment]
Apache 2.0 is preferred as per http://source.android.com/source/licenses.html

I would appreciate Apache 2.0 as I'm looking at using this in our application. We'd also be interested in making some more enhancements and performance profiling/tuning it assuming we end up using it.

**Comment by EddieRingle** [comment]
As long as it's not LGPL, they don't care. ;)

"we do in fact prefer ASL2.0 (and similar licenses like BSD, MIT, etc.) over other licenses such as LGPL."

**Comment by dallasgutauckis** [comment]
You caught me trying to trick you into using Apache... good on you.

**Comment by pplante** [comment]
i would love to use this library, but the lack of a license is prohibiting me from doing so.  will you be able to attach a license soon?

**Comment by uKL** [comment]
When can we expect seeing the license? :) Regards!
