### ISSUE TITLE
Is there a way to  configure the amount of slide?

### ISSUE THREAD

**Issue by itamecodes** [EddieRingle/android-undergarment#2]
As of now the drawer menu slides over the entire screen.. Is there a way to override this?

**Comment by pplante** [comment]
I just ran into this issue myself.  Looking at the openDrawer() method it seems the width of the drawer is calculated on the fly at the top with:

`final int widthPixels = getResources().getDisplayMetrics().widthPixels;
        mScroller
                .startScroll(mDecorOffsetX, 0, (widthPixels - mTouchTargetWidth) - mDecorOffsetX, 0,
                                    SCROLL_DURATION);`

I guess a configurable max width would fix this?

**Comment by EddieRingle** [comment]
You can now configure both the touch target width (the minimum width the content area will essentially shrink to; default is 48dp) and the maximum drawer width (can be WRAP_CONTENT, MATCH_PARENT, or another pixel value). Use the `setTouchTargetWidth` and `setDrawerMaxWidth` methods, respectively.

I did a few tests locally and it seems to work alright, but give it a try and let me know if you hit any issues.
