### ISSUE TITLE
Add feature to populate drawer with XML resource

### ISSUE THREAD

**Issue by AlexNab** [EddieRingle/android-undergarment#5]
Typical drawer menu implementation usually has a list of menu items.
So it would be great to have some bundled helpers to populate drawer with XML resource that describes desired drawer menu items. This will quicken development by obviating necessity of creating custom drawer layout, Adapter, layout for list item, etc.

True, that some drawer menus (e.g. in YouTube, Evernote apps) have complex custom layout also. So, to support both cases there can be API to set menu resource to inflate and custom view also. By the way, similar approach is implemented in FlyInMenu library by Alex Curran:
https://github.com/Espiandev/FlyInMenu

It populates menu items (icon+label) from XML menu resource with content like this:
https://github.com/Espiandev/FlyInMenu/blob/master/sample/res/menu/ribbon_menu.xml

Also it has API to add custom view also:
`<getFlyInMenu().setCustomView(..)>`

**Comment by EddieRingle** [comment]
Revisiting this issue today; I don't think it's within the scope of this project. Undergarment is simply a control for implementing the slide-out drawer pattern. The content that drawer contains is left entirely up to the developer. That keeps things simple and is why I think it's best if I just leave it at specifying a layout to populate the drawer with. Going along that route, a more appropriate solution for your problem would be a custom Fragment--created during the inflation of the drawer's layout resource--that builds a menu using XML resources as you've described.
