### ISSUE TITLE
DecorContent is still active when the drawer is open

### ISSUE THREAD

**Issue by laurencedawson** [EddieRingle/android-undergarment#9]
When the drawer is open, I don't think the DecorContent should be active. 

For example clicking a button in the DecorContent will still work AND close the drawer. The button should not be clickable at all and all touch events should simply close the drawer.

**Comment by laurencedawson** [comment]
Are there any plans to add this?

**Comment by EddieRingle** [comment]
In the two applications I have here, the content area is disabled properly and no touch events appear to pass through (only the drawer is closed). What sort of situation are you seeing this behavior appear?

**Comment by laurencedawson** [comment]
For the most basic example, I create the drawer. When it slides out all content is clickable but when clicked will click the content area and close the drawer.

`DrawerGrarment mDrawerGarment = new DrawerGarment(this, R.layout.slidingdrawer_contents);`

**Comment by laurencedawson** [comment]
It might be worth noting that even ActionBar items are clickable still.

**Comment by EddieRingle** [comment]
If you set the slide target to `SLIDE_TARGET_CONTENT` with `mDrawerGarment.setSlideTarget(SLIDE_TARGET_CONTENT)`, does the problem disappear?

**Comment by laurencedawson** [comment]
Sadly not, exactly the same problem. I can upload a basic example showing this problem if you want?

**Comment by EddieRingle** [comment]
Yes please!

**Comment by laurencedawson** [comment]
https://github.com/laurencedawson/example_slide

You should be able to import that as a project directly into eclipse. So the button is still clickable even when the drawer is open. Thanks for your help sorting this!

**Comment by EddieRingle** [comment]
Yes, I see the issue now (including a rare case on one of my other applications). I'll look into a better way of handling this. Thanks for bringing it up!

**Comment by laurencedawson** [comment]
If we could access the ViewGroup of the content we could just intercept the touch if mDrawerMoving.
